# Gitlab continuous integration script
# for ram

stages:
  - build
  - test
  - test-generate

build:
  image: rust:1.39-stretch
  stage: build 
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
  cache:
    paths:
      - target/
      - cargo/
  script:
    cargo build --release
  artifacts:
    paths:
      - target/release/ram

codecov:
  image: xd009642/tarpaulin
  stage: test
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
  cache:
    paths:
      - target/
      - cargo/
  script:
    - cargo tarpaulin

# Tests for example configurations and templates
rust-rocket:
  stage: test-generate
  image: rust:1.39-stretch
  script:
    - target/release/ram -c examples/rust/rocket/rocket.yaml -i examples/openapi/farm.yaml -o examples/rust/rocket/src
    - cd examples/rust/rocket
    - rustup toolchain add nightly
    - cargo +nightly build

rust-actix:
  stage: test-generate
  image: rust:1.39-stretch
  script:
    - target/release/ram -c examples/rust/actix/actix.yml -i examples/openapi/farm.yaml -o examples/rust/actix/src
    - cd examples/rust/actix
    - cargo build

go-echo:
  stage: test-generate
  image: golang:1.13
  script:
    - target/release/ram -c examples/go/echo/config.yaml -i examples/openapi/farm.yaml -o examples/go/echo
    - cd examples/go/echo
    - go get -u github.com/labstack/echo/...
    - go build
      
go-squirrel:
  stage: test-generate
  image: golang:1.13
  script:
    - target/release/ram -c examples/go/squirrel/templates/config.yaml -i examples/openapi/farm.yaml -o examples/go/squirrel
    - cd examples/go/squirrel
    - go get -u github.com/Masterminds/squirrel
    - go get -u github.com/jmoiron/sqlx
    - go build

java-models:
  stage: test-generate
  image: openjdk:latest
  script:
    - target/release/ram -c examples/java/models/config.yaml -i examples/openapi/farm.yaml -o examples/java/models/src
    - cd examples/java/models
    # TODO: main file
    - javac main.java
