# Gitlab continuous integration script
# for ram

stages:
  - build
  - test-generate

# Adds target bin folder to path
variables:
  PATH: $PATH:$CI_PROJECT_DIR/target/release

build:
  image: rust:1.39-stretch
  stage: build 
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
  cache:
    paths:
      - target/
      - cargo/
  script:
    cargo build --release
  artifacts:
    paths:
      - target/release/ram

# Tests for example configurations and templates
rust-rocket:
  stage: test-generate
  image: rust:nightly
  script:
    - ram -c examples/rust/rocket/rocket.yaml -i examples/openapi/farm.yaml -o examples/rust/rocket/src
    - cd examples/rust/rocket
    - cargo build

rust-actix:
  stage: test-generate
  image: rust:1.39-stretch
  script:
    - ram -c examples/rust/actix/actix.yml -i examples/openapi/farm.yaml -o examples/rust/actix/src
    - cd examples/rust/actix
    - cargo build

go-models:
  stage: test-generate
  image: golang:1.13
  script:
    - ram -c examples/go/models_only/config.yaml -i examples/openapi/farm.yaml -o examples/go/models_only
    - cd examples/go/models_only
    - go build

go-echo:
  stage: test-generate
  image: golang:1.13
  script:
    - ram -c examples/go/echo/config.yaml -i examples/openapi/farm.yaml -o examples/go/echo
    - cd examples/go/echo
    - go get -u github.com/labstack/echo/...
    - go build
