# Example ram config file

# OpenAPI specification file
openapi: "./res/petstore.yaml"

# Target lang spec
# Can be file or built-in yaml spec
lang: "rust"

# Template files
templates:
  model: "templates/model.rs.mustache"
  api: "templates/api.rs.mustache"

paths:
  root: "output/src"
