# Example ram config file

# OpenAPI specification file
openapi_spec: "./res/petstore.yaml"

# Target lang spec
# Can be file or built-in yaml spec
lang_spec: "rust"

# Template files
template:
  model: "templates/model.rs.template"
  api: "templates/api.rs.template"
