# Example ram config file

# OpenAPI specification file
openapi: "./res/petstore.yaml"

# Target lang spec
# Can be file or built-in yaml spec
lang: "rust"

# Template files
template:
  model: "templates/model.rs.mustache"
  api: "templates/api.rs.mustache"

# Used for modules and namespace mapping
namespace:
  model: 'petstore_models'

# File paths
paths:
  model: 'src/models'
