[package]
name = "ram"
description = "Rusty API Modeler. Generates models from openapi spec."
license = "MIT"
homepage = "https://github.com/alamminsalo/ram"
repository = "https://github.com/alamminsalo/ram"
version = "0.5.0"
authors = ["alamminsalo <antti.lamminsalo@protonmail.com>"]
edition = "2018"
exclude = [
    "example/"
]

[lib]
name = "ram"
path = "src/lib.rs"

[[bin]]
name = "ram"
path = "src/main.rs"

[dependencies]
serde = {version = "1.0.98", features = ["derive"] }
serde_json = "1.0.40"
failure = "0.1.5"
serde_yaml = "0.8.9"
openapi = { git = "https://github.com/alamminsalo/openapi", branch = "schema_collect" }
Inflector = "0.11.4"
rust-embed = "5.1.0"
htmlescape = "0.3.1"
handlebars = "2.0.2"
glob = "0.3.0"
maplit = "1.0.2"
