[package]
name = "ram"
version = "0.1.0"
authors = ["alamminsalo <antti.lamminsalo@protonmail.com>"]
edition = "2018"

[lib]
name = "ram"
path = "src/lib.rs"

[[bin]]
name = "ram-cli"
path = "src/main.rs"

[dependencies]
serde = {version = "1.0.98", features = ["derive"] }
serde_json = "1.0.40"
failure = "0.1.5"
serde_yaml = "0.8.9"
openapi = { path = "../openapi" }
mustache = "0.9.0"
htmlescape = "0.3.1"
handlebars = "2.0.2"
