openapi: "3.0.0"
info:
  title: Test for object reference collect
  version: v2
paths:
  /farm:
    get:
      responses:
        '200':
          description: "get farm content"
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Farm"
components:
  schemas:
    Farm:
      x-sql-table: "farm"
      x-sql-pk: "id"
      properties:
        id:
          type: integer
        tails:
          $ref: "extra/animals.yaml#/Dog"
        claws:
          $ref: "extra/animals.yaml#/Cat"
          nullable: true
        herd: 
          type: array
          items:
            $ref: "extra/animals.yaml#/Cow"
          x-sql-m2m: "farm_cows"
          x-sql-m2m-table: "cow"
          x-sql-m2m-pk: "id"
      additionalProperties:
        properties:
          hidden:
            $ref: "extra/loop.yaml#/Loop"
            nullable: true
          numbers:
            type: array
            items:
              type: integer
          dogId:
            type: integer
            x-sql-fk: "dog(id)"
          catId:
            type: integer
            x-sql-fk: "cat(id)"
