name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install bin
      run: cargo install --path .

    - name: Generate Rust (Rocket)
      run: |
        ram -c examples/rust/rocket/rocket.yaml -i examples/openapi/farm.yaml -o examples/rust/rocket/src
        cd examples/rust/rocket
        cargo build

    - name: Generate Rust (Actix)
      run: |
        ram -c examples/rust/actix/actix.yml -i examples/openapi/farm.yaml -o examples/rust/actix/src
        cd examples/rust/actix
        cargo build

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12

    - name: Generate Go (models only)
      run: |
        ram -c examples/go/models_only/config.yaml -i examples/openapi/farm.yaml -o examples/go/models_only
        cd examples/go/models_only
        go build

    - name: Generate Go (Echo server)
      run: |
        ram -c examples/go/echo/config.yaml -i examples/openapi/farm.yaml -o examples/go/echo
        cd examples/go/echo
        go get -u github.com/labstack/echo/...
        go build
