name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release build
      run: | 
        cargo build --release
        export PATH="$PATH:$(pwd)/target/release"
        echo $PATH

    - name: Generate Rust
      run: |
        cd examples/rust
        ram
        cargo build

